export const DICCIONARIO: any = {
  "es": {
    "bienvenido": "Bienvenidos a Restaurante Prototipo",
    "experiencia": "La verdadera experiencia de la cocina artesanal en tu mesa.",
    "pasion": "Nuestra Pasión",
    "prototipo": "Restaurante Prototipo, seleccionamos los ingredientes más frescos del mercado local para crear platos que cuentan una historia. Desde nuestras carnes braseadas hasta nuestras opciones vegetarianas, cada bocado es un viaje de sensaciones.",
    "ingredientes": "Ingredientes Orgánicos",
    "trabajamos": "Trabajamos con productores locales para asegurar la máxima calidad.",
    "cocina": "Cocina a la Leña",
    "ahumado": "El sabor ahumado que nos hace únicos en la ciudad.",
    "vinos": "Cava de Vinos",
    "seleccion": "La mejor selección para maridar tus momentos especiales.",
    "idioma": "Modificar Idioma",
    "nombre_idioma": "Español",
    "carta": "Explorar nuestra Carta Completa",
    "cargarIdioma": "Cargar Idioma",
    "obtenerIdioma": "Obtener Idioma Geolocalizado",
    "menu_titulo": "Nuestra Carta",
    "menu_subtitulo": "Sabores seleccionados para deleitar tus sentidos",
    "cat_entradas": "Entradas",
    "cat_principales": "Platos Principales",
    "btn_agregar": "Agregar al pedido",
    "btn_volver": "Volver al Inicio",
    "p1_nombre": "Burrata Artesanal",
    "p1_desc": "Corazón cremoso con tomates cherry confitados y pesto de albahaca fresca.",
    "p2_nombre": "Empanadas de Cordero",
    "p2_desc": "Tres unidades cocidas a la leña con salsa criolla suave.",
    "p3_nombre": "Ojo de Bife Prototipo",
    "p3_desc": "400g de carne premium con papas rústicas y manteca de chimichurri.",
    "p4_nombre": "Risotto de Hongos",
    "p4_desc": "Arroz carnaroli con variedad de hongos de estación y trufa negra.",
    "p5_nombre": "Salmón a la Plancha",
    "p5_desc": "Filete de salmón rosado con puré de calabaza y semillas tostadas.",
    "seleccionar": "Seleccione el lugar al que desea cambiar el idioma",
    "confirmar": "Confirmar selección",
    "error_titulo": "No se ha podido agregar el idioma",
    "error_desc": "Idioma no reconocido o fuera de los límites, cambiando a español por defecto",
    "exito_titulo": "¡Listo!",
    "exito_desc": "Ubicación guardada con éxito",
    "cambio": "El idioma seleccionado es ",
    "OK": "Aceptar",
    "geo_error_titulo": "Ubicación Desactivada",
    "geo_error_desc": "Permisos rechazados. Por favor, acepte los permisos de ubicación para habilitar esta función automática."
  },
  "en": {
    "bienvenido": "Welcome to Prototype Restaurant",
    "experiencia": "The true experience of artisanal cuisine at your table.",
    "pasion": "Our Passion",
    "prototipo": "At Prototype Restaurant, we select the freshest ingredients from the local market to create dishes that tell a story. From our braised meats to our vegetarian options, every bite is a journey of sensations.",
    "ingredientes": "Organic Ingredients",
    "trabajamos": "We work with local producers to ensure maximum quality.",
    "cocina": "Wood-Fired Kitchen",
    "ahumado": "The smoky flavor that makes us unique in the city.",
    "vinos": "Wine Cellar",
    "seleccion": "The best selection to pair with your special moments.",
    "idioma": "Change Language",
    "nombre_idioma": "English",
    "carta": "Explore our Full Menu",
    "cargarIdioma": "Load Language",
    "obtenerIdioma": "Get Geolocated Language",
    "menu_titulo": "Our Menu",
    "menu_subtitulo": "Selected flavors to delight your senses",
    "cat_entradas": "Appetizers",
    "cat_principales": "Main Courses",
    "btn_agregar": "Add to order",
    "btn_volver": "Back to Home",
    "p1_nombre": "Artisanal Burrata",
    "p1_desc": "Creamy heart with candied cherry tomatoes and fresh basil pesto.",
    "p2_nombre": "Lamb Empanadas",
    "p2_desc": "Three wood-fired units with mild Creole sauce.",
    "p3_nombre": "Prototype Ribeye",
    "p3_desc": "400g premium beef with rustic potatoes and chimichurri butter.",
    "p4_nombre": "Mushroom Risotto",
    "p4_desc": "Carnaroli rice with variety of seasonal mushrooms and black truffle.",
    "p5_nombre": "Grilled Salmon",
    "p5_desc": "Pink salmon fillet with pumpkin puree and toasted seeds.",
    "seleccionar": "Select the location to change the language",
    "confirmar": "Confirm selection",
    "error_titulo": "Could not add the language",
    "error_desc": "Language not recognized or out of bounds, switching to Spanish by default",
    "exito_titulo": "Done!",
    "exito_desc": "Location saved successfully",
    "cambio": "The selected language is ",
    "OK": "OK",
    "geo_error_titulo": "Location Disabled",
    "geo_error_desc": "Permissions denied. Please accept location permissions to enable this automatic feature."
  },
  "pt": {
    "bienvenido": "Bem-vindos ao Restaurante Protótipo",
    "experiencia": "A verdadeira experiência da cozinha artesanal na sua mesa.",
    "pasion": "Nossa Paixão",
    "prototipo": "No Restaurante Protótipo, selecionamos os ingredientes mais frescos do mercado local para criar pratos que contam uma história. Das nossas carnes assadas às nossas opções vegetarianas, cada mordida é uma viagem de sensações.",
    "ingredientes": "Ingredientes Orgânicos",
    "trabajamos": "Trabalhamos com produtores locais para garantir a máxima qualidade.",
    "cocina": "Cozinha a Lenha",
    "ahumado": "O sabor defumado que nos torna únicos na cidade.",
    "vinos": "Adega de Vinhos",
    "seleccion": "A melhor seleção para harmonizar com seus momentos especiais.",
    "idioma": "Alterar Idioma",
    "nombre_idioma": "Português",
    "carta": "Explorar nosso Menu Completo",
    "cargarIdioma": "Carregar Idioma",
    "obtenerIdioma": "Obter Idioma Geolocalizado",
    "menu_titulo": "Nosso Cardápio",
    "menu_subtitulo": "Sabores selecionados para deleitar seus sentidos",
    "cat_entradas": "Entradas",
    "cat_principales": "Pratos Principais",
    "btn_agregar": "Adicionar ao pedido",
    "btn_volver": "Voltar ao Início",
    "p1_nombre": "Burrata Artesanal",
    "p1_desc": "Coração cremoso con tomates cereja confitados e pesto de manjericão fresco.",
    "p2_nombre": "Empanadas de Cordeiro",
    "p2_desc": "Três unidades assadas no fogão a lenha com molho crioulo suave.",
    "p3_nombre": "Ojo de Bife Protótipo",
    "p3_desc": "400g de carne premium com batatas rústicas e manteiga de chimichurri.",
    "p4_nombre": "Risoto de Cogumelos",
    "p4_desc": "Arroz carnaroli com variedade de cogumelos da estação e trufas negras.",
    "p5_nombre": "Salmão na Grelha",
    "p5_desc": "Filé de salmão rosado com purê de abóbora e sementes torradas.",
    "seleccionar": "Selecione o local para o qual deseja alterar o idioma",
    "confirmar": "Confirmar seleção",
    "error_titulo": "Não foi possível adicionar o idioma",
    "error_desc": "Idioma não reconhecido ou fora dos limites, mudando para espanhol por padrão",
    "exito_titulo": "Pronto!",
    "exito_desc": "Localização salva com sucesso",
    "cambio": "O idioma selecionado é ",
    "OK": "Aceitar",
    "geo_error_titulo": "Localização Desativada",
    "geo_error_desc": "Permissões rejeitadas. Por favor, aceite as permissões de localização para ativar esta função automática."
  },
  "fr": {
    "bienvenido": "Bienvenue au Restaurant Prototype",
    "experiencia": "La véritable expérience de la cuisine artisanale à votre table.",
    "pasion": "Notre Passion",
    "prototipo": "Au Restaurant Prototype, nous sélectionnons les ingrédients les plus frais du marché local pour créer des plats qui racontent une histoire. De nos viandes braisées à nos options végétariennes, chaque bouchée est un voyage des sens.",
    "ingredientes": "Ingrédients Biologiques",
    "trabajamos": "Nous travaillons avec des producteurs locaux pour assurer une qualité maximale.",
    "cocina": "Cuisine au Feu de Bois",
    "ahumado": "Le goût fumé qui nous rend uniques en ville.",
    "vinos": "Cave à Vins",
    "seleccion": "La meilleure selección pour accompagner vos moments spéciaux.",
    "idioma": "Modifier la Langue",
    "nombre_idioma": "Français",
    "carta": "Explorer notre Carte Completa",
    "cargarIdioma": "Charger la Langue",
    "obtenerIdioma": "Obtenir la Langue Géolocalisée",
    "menu_titulo": "Notre Carte",
    "menu_subtitulo": "Des saveurs sélectionnées pour ravir vos sens",
    "cat_entradas": "Entrées",
    "cat_principales": "Platos Principales",
    "btn_agregar": "Ajouter à la commande",
    "btn_volver": "Retour à l'accueil",
    "p1_nombre": "Burrata Artisanale",
    "p1_desc": "Cœur crémeux avec tomates cerises confites et pesto de basilic frais.",
    "p2_nombre": "Empanadas d'Agneau",
    "p2_desc": "Trois unités cuites au feu de bois avec une sauce créole douce.",
    "p3_nombre": "Faux-filet Prototype",
    "p3_desc": "400g de bœuf premium avec pommes de terre rustiques et beurre chimichurri.",
    "p4_nombre": "Risotto aux Champignons",
    "p4_desc": "Riz carnaroli avec une variété de champignons de saison et truffe noire.",
    "p5_nombre": "Saumon Grillé",
    "p5_desc": "Filet de saumon rose avec purée de potiron et graines grillées.",
    "seleccionar": "Sélectionnez le lieu vers lequel vous souhaitez changer la langue",
    "confirmar": "Confirmer la sélection",
    "error_titulo": "Impossible d'ajouter la langue",
    "error_desc": "Langue non reconnue ou hors limites, passage à l'espagnol par défaut",
    "exito_titulo": "Terminé !",
    "exito_desc": "Emplacement enregistré avec succès",
    "cambio": "La langue sélectionnée est ",
    "OK": "Accepter",
    "geo_error_titulo": "Localisation Désactivée",
    "geo_error_desc": "Autorisations refusées. Veuillez accepter les autorisations de localisation pour activer cette fonction automatique."
  },
  "de": {
    "bienvenido": "Willkommen im Restaurant Prototyp",
    "experiencia": "Das wahre Erlebnis handwerklicher Küche an Ihrem Tisch.",
    "pasion": "Unsere Leidenschaft",
    "prototipo": "Im Restaurant Prototyp wählen wir die frischesten Zutaten vom lokalen Markt aus, um Gerichte zu kreieren, die eine Geschichte erzählen. Von unserem geschmorten Fleisch bis hin zu unseren vegetarischen Optionen ist jeder Bissen eine Reise der Sinne.",
    "ingredientes": "Bio-Zutaten",
    "trabajamos": "Wir arbeiten mit lokalen Erzeugern zusammen, um höchste Qualität zu gewährleisten.",
    "cocina": "Holzofen-Küche",
    "ahumado": "Der rauchige Geschmack, der uns in der Stadt einzigartig macht.",
    "vinos": "Weinkeller",
    "seleccion": "Die beste Auswahl für Ihre besonderen Momente.",
    "idioma": "Sprache ändern",
    "nombre_idioma": "Deutsch",
    "carta": "Entdecken Sie unsere vollständige Karte",
    "cargarIdioma": "Sprache laden",
    "obtenerIdioma": "Geolokalisierte Sprache abrufen",
    "menu_titulo": "Unsere Speisekarte",
    "menu_subtitulo": "Ausgewählte Aromen, um Ihre Sinne zu verwöhnen",
    "cat_entradas": "Vorspeisen",
    "cat_principales": "Hauptgerichte",
    "btn_agregar": "Bestellung hinzufügen",
    "btn_volver": "Zurück zum Start",
    "p1_nombre": "Handwerklich hergestellte Burrata",
    "p1_desc": "Cremiges Herz mit kandierten Cherrytomaten und frischem Basilikum-Pesto.",
    "p2_nombre": "Lamm-Empanadas",
    "p2_desc": "Drei im Holzofen gegarte Einheiten mit milder kreolischer Sauce.",
    "p3_nombre": "Prototyp-Rumpsteak",
    "p3_desc": "400g Premium-Rindfleisch mit rustikalen Kartoffeln und Chimichurri-Butter.",
    "p4_nombre": "Pilz-Risotto",
    "p4_desc": "Carnaroli-Reis mit verschiedenen Pilzen der Saison und schwarzem Trüffel.",
    "p5_nombre": "Gegrillter Lachs",
    "p5_desc": "Rosa Lachsfilet mit Kürbispüree und gerösteten Kernen.",
    "seleccionar": "Wählen Sie den Ort aus, an den Sie die Sprache ändern möchten",
    "confirmar": "Auswahl bestätigen",
    "error_titulo": "Sprache konnte nicht hinzugefügt werden",
    "error_desc": "Sprache nicht erkannt oder außerhalb der Grenzen, standardmäßig auf Spanisch umgestellt",
    "exito_titulo": "Fertig!",
    "exito_desc": "Standort erfolgreich gespeichert",
    "cambio": "Die gewählte Sprache ist ",
    "OK": "Verstanden",
    "geo_error_titulo": "Standort Deaktiviert",
    "geo_error_desc": "Berechtigungen abgelehnt. Bitte akzeptieren Sie die Standortberechtigungen, um diese automatische Funktion zu aktivieren."
  },
  "ru": {
    "bienvenido": "Добро пожаловать в Ресторан Прототип",
    "experiencia": "Истинный вкус ремесленной кухни на вашем столе.",
    "pasion": "Наша Страсть",
    "prototipo": "В Ресторане Прототип мы выбираем самые свежие ингредиенты с местного рынка, чтобы создавать блюда, рассказывающие историю. От тушеного мяса до вегетарианских блюд — каждый кусочек — это путешествие чувств.",
    "ingredientes": "Органические ингредиенты",
    "trabajamos": "Мы работаем с местными производителями, чтобы гарантировать максимальное качество.",
    "cocina": "Кухня на дровах",
    "ahumado": "Дымный аромат, который делает нас уникальными в городе.",
    "vinos": "Винный погреб",
    "seleccion": "Лучший выбор для ваших особенных моментов.",
    "idioma": "Изменить язык",
    "nombre_idioma": "Русский",
    "carta": "Посмотреть полное меню",
    "cargarIdioma": "Загрузить язык",
    "obtenerIdioma": "Получить язык по геолокации",
    "menu_titulo": "Наше Меню",
    "menu_subtitulo": "Отобранные вкусы, чтобы порадовать ваши чувства",
    "cat_entradas": "Закуски",
    "cat_principales": "Основные блюда",
    "btn_agregar": "Добавить в заказ",
    "btn_volver": "Вернуться на главную",
    "p1_nombre": "Крафтовая Буррата",
    "p1_desc": "Сливочное сердце с засахаренными томатами черри и песто из свежего базилика.",
    "p2_nombre": "Эмпанадас с ягненком",
    "p2_desc": "Три штуки, приготовленные на дровах с мягким креольским соусом.",
    "p3_nombre": "Рибай Прототип",
    "p3_desc": "400 г говядины высшего качества с деревенским картофелем и маслом чимичурри.",
    "p4_nombre": "Ризотто с грибами",
    "p4_desc": "Рис карнароли с ассорти из сезонных грибов и черным трюфелем.",
    "p5_nombre": "Лосось на гриле",
    "p5_desc": "Филе розового лосося с тыквенным пюре и обжаренными семенами.",
    "seleccionar": "Выберите место, на которое вы хотите изменить язык",
    "confirmar": "Подтвердить выбор",
    "error_titulo": "Не удалось добавить язык",
    "error_desc": "Язык не распознан или находится вне границ, по умолчанию переключено на испанский",
    "exito_titulo": "Готово!",
    "exito_desc": "Местоположение успешно сохранено",
    "cambio": "Выбранный язык: ",
    "OK": "Понятно",
    "geo_error_titulo": "Геолокация отключена",
    "geo_error_desc": "В разрешении отказано. Пожалуйста, разрешите доступ к местоположению для включения автоматической функции."
  }
};